# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Maven Build & Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      if: ${{ github.ref != 'refs/heads/master' }}
      run: mvn clean package --file pom.xml
      
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Publish package
      if: contains(github.ref, 'release')
      run: mvn clean -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} --batch-mode deploy -DskipTests=true -P release
      env:
        MAVEN_USERNAME: ${{ secrets.MVN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
